# Generated by Django 5.1.4 on 2025-01-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=120)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField(default='')),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('fa', 'Fashion'), ('el', 'Electronics'), ('hk', 'Home and Kitchen'), ('bc', 'Beauty and Personal Care'), ('so', 'Sports and Outdoors'), ('bs', 'Books and Stationery'), ('tg', 'Toys and Games'), ('hw', 'Health and Wellness'), ('au', 'Automotive'), ('ps', 'Pet Supplies'), ('gr', 'Groceries and Essentials'), ('ja', 'Jewelry and Accessories')], max_length=2)),
                ('product_img', models.ImageField(upload_to='product')),
            ],
        ),
    ]
