# Generated by Django 5.1.4 on 2025-01-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortform', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('product_count', models.IntegerField(default=0)),
                ('category_img', models.ImageField(upload_to='category')),
            ],
        ),
    ]
