# Generated by Django 5.1.4 on 2025-01-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0005_remove_orderplaced_payment_remove_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='orderId',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
